steps:
  # Step to aggregate secrets into .env file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "AUTH_PROVIDER_X509_CERT_URL=$$SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL" > .env
        echo "AUTH_URI=$$SERVICE_ACCOUNT_AUTH_URI" >> .env
        echo "CLIENT_EMAIL=$$SERVICE_ACCOUNT_CLIENT_EMAIL" >> .env
        echo "CLIENT_ID=$$SERVICE_ACCOUNT_CLIENT_ID" >> .env
        echo "CLIENT_X509_CERT_URL=$$SERVICE_ACCOUNT_CLIENT_X509_CERT_URL" >> .env
        echo "PRIVATE_KEY_ID=$$SERVICE_ACCOUNT_PRIVATE_KEY_ID" >> .env
        echo "PROJECT_ID=$$SERVICE_ACCOUNT_PROJECT_ID" >> .env
        echo "TOKEN_URI=$$SERVICE_ACCOUNT_TOKEN_URI" >> .env
        echo "TYPE=$$SERVICE_ACCOUNT_TYPE" >> .env
        echo "UNIVERSE_DOMAIN=$$SERVICE_ACCOUNT_UNIVERSE_DOMAIN" >> .env
    secretEnv: [
      'SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL',
      'SERVICE_ACCOUNT_AUTH_URI',
      'SERVICE_ACCOUNT_CLIENT_EMAIL',
      'SERVICE_ACCOUNT_CLIENT_ID',
      'SERVICE_ACCOUNT_CLIENT_X509_CERT_URL',
      'SERVICE_ACCOUNT_PRIVATE_KEY_ID',
      'SERVICE_ACCOUNT_PROJECT_ID',
      'SERVICE_ACCOUNT_TOKEN_URI',
      'SERVICE_ACCOUNT_TYPE',
      'SERVICE_ACCOUNT_UNIVERSE_DOMAIN'
    ]

  # Your build steps follow here
  - name: 'node:20'
    entrypoint: npm
    args: ['install']

  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']

availableSecrets:
  secretManager:
    - versionName: projects/879567069316/secrets/SERVICE_ACCOUNT_CLIENT_X509_CERT_URL
      env: 'SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL'
    - versionName: projects/879567069316/secrets/SERVICE_ACCOUNT_AUTH_URI
      env: 'SERVICE_ACCOUNT_AUTH_URI'
    - versionName: projects/879567069316/secrets/SERVICE_ACCOUNT_CLIENT_EMAIL
      env: 'SERVICE_ACCOUNT_CLIENT_EMAIL'
    - versionName: projects/879567069316/secrets/SERVICE_ACCOUNT_CLIENT_ID
      env: 'SERVICE_ACCOUNT_CLIENT_ID'
    - versionName: projects/879567069316/secrets/SERVICE_ACCOUNT_CLIENT_X509_CERT_URL
      env: 'SERVICE_ACCOUNT_CLIENT_X509_CERT_URL'
    - versionName: projects/879567069316/secrets/SERVICE_ACCOUNT_PRIVATE_KEY_ID
      env: 'SERVICE_ACCOUNT_PRIVATE_KEY_ID'
    - versionName: projects/879567069316/secrets/SERVICE_ACCOUNT_PROJECT_ID
      env: 'SERVICE_ACCOUNT_PROJECT_ID'
    - versionName: projects/879567069316/secrets/SERVICE_ACCOUNT_TOKEN_URI
      env: 'SERVICE_ACCOUNT_TOKEN_URI'
    - versionName: projects/879567069316/secrets/SERVICE_ACCOUNT_TYPE
      env: 'SERVICE_ACCOUNT_TYPE'
    - versionName: projects/879567069316/secrets/SERVICE_ACCOUNT_UNIVERSE_DOMAIN
      env: 'SERVICE_ACCOUNT_UNIVERSE_DOMAIN'
    - versionName: projects/879567069316/secrets/SERVICE_ACCOUNT_PRIVATE_KEY
      env: 'SERVICE_ACCOUNT_PRIVATE_KEY'