name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_CLI_EXPERIMENTS: webframeworks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode Firebase Service Account JSON
        env:
          BASE64_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
        run: echo "$BASE64_KEY" | base64 --decode > firebase-admin-key.json

      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v1.1
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: firebase-admin-key.json
          channelId: live
          projectId: samplermj
