name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_CLI_EXPERIMENTS: webframeworks
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and build
        run: npm ci && npm run build