name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_CLI_EXPERIMENTS: webframeworks
    steps:
      - uses: actions/checkout@v4

      - name: Create Service Account Key File
       run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAMPLERMJ }}" > $GITHUB_WORKSPACE/service-account-key.json
      - name: Debug JSON Key
        run: |
          echo "Contents of service-account-key.json:"
          cat $GITHUB_WORKSPACE/service-account-key.json
          echo "End of file."
          
      - name: Install dependencies and build
        run: npm ci && npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAMPLERMJ }}
          channelId: live
          projectId: samplermj